language: node_js
node_js:
- 12
addons:
  ssh_known_hosts: 107.167.181.223
after_success:
- echo 'I successfully done'
- ssh root@107.167.181.223 'cat /etc/issue'
install:
- npm install -g mocha
- cd server && npm install && npm install chai  chai-http @babel/core @babel/register @babel/polyfill
- cd ../client && npm install && npm run build --prod
before_install:
- openssl aes-256-cbc -K $encrypted_9b2d7e19d83c_key -iv $encrypted_9b2d7e19d83c_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa